publishDir = "public"
baseurl = "https://sherlockes.github.io"
title = "Sherblog"
languageCode = "es"
DefaultContentLanguage = "es"
paginate = "9" # Number of posts per page
rssLimit = "10"
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
    name = "Sherlockes"
    bio = "Solo un discípulo de San Google..."
    avatar = "img/avatar.png"

[permalinks]
    post = "/:title/"

[related]
  includeNewer = true
  threshold = 85
  toLower = false

  [[related.indices]]
  name = "tags"
  weight = 80

  [[related.indices]]
  name = "categories"
  weight = 70

  [[related.indices]]
  name = "keywords"
  weight = 40

  [[related.indices]]
  name = "date"
  weight = 10

[Params]
  subtitle = "Sólo mi forma de hacer las cosas..."
  description = "Un poco de informática, bricolaje, bicicleta y todos los problemas que se me ponen delante en el día a día no está de más documentarlos, a alguien le puede ayudar..."
  copyright = "Sherlockes" #
  opengraph = true
  twitter_cards = true
  readmore = false
  authorbox = false
  disable_comments = true
  toc = true
  pager = true
  post_navigation = true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["post"]
  dateformat = "2006-01-02"
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages

  # Enable widgets in given order
  # widgets = ["social", "recent", "categories", "taglist"]
  widgets = ["social", "categories", "taglist"]

[Params.widgets]
  recent_num = 10 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  mastodon = "@sherlockes"
  twitter = "sherblogpro"
  telegram = "sherlockes"
  github = "sherlockes"
  youtube = "UCkx4Zgs1ujSuVsxcOFuGCoQ"
  strava = "11156844"
