name: Convert Thumbnails to 16:9

on:
  push:
    paths:
      - 'static/images/*00.jpg'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Convert square thumbnails to 16:9
        run: |
          for img in images/*00.jpg; do
            filename=$(basename "$img")
            extension="${filename##*.}"
            base="${filename%.*}"
            width=$(identify -format "%w" "$img")
            height=$(identify -format "%h" "$img")
            new_width=$(( height * 16 / 9 ))
            convert "$img" -gravity center -background white -extent "${new_width}x${height}" "images/${base}_xl.${extension}"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add images/*_xl.jpg
          git commit -m "Auto-generate 16:9 thumbnails"
          git push
        continue-on-error: true
